cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/jack/Documents/homework/CS169/angry_pkt_work/adtcp2/ns-allinone-3.18/ns-3.18/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/jack/Documents/homework/CS169/angry_pkt_work/adtcp2/ns-allinone-3.18/ns-3.18/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 147884140: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'-lstl\', \'test.cpp.1.o\', \'-o\', \'/home/jack/Documents/homework/CS169/angry_pkt_work/adtcp2/ns-allinone-3.18/ns-3.18/build/.conf_check_13faad937b5f71a571170721db92961a/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-llstl\']\n'
